name: ci
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.17.x
          - 1.16.x
        os:
          - macos
          - ubuntu
          - windows

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: make build

  test:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.17.x
          - 1.16.x
        os:
          - macos
          - ubuntu

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: make test
    
  test_windows:
    strategy:
      matrix:
        go-version:
          - 1.18.x
          - 1.17.x
          - 1.16.x
        os:
          - windows

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    # tests fail in windows if the race flag is used
    - run: make test_without_race

  qa:
    strategy:
      matrix:
        go-version:
          - 1.18.x
        os:
          - ubuntu

    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: make check-fmt
    - run: make vet
    - run: go install honnef.co/go/tools/cmd/staticcheck@v0.3.0
    - run: make staticcheck
    - run: go install mvdan.cc/unparam@latest
    - run: make unparam
